### ISSUE TITLE
Error trying to flash SkyConnect to Zigbee only firmware

### ISSUE THREAD

**Issue by MiloRoNu** [NabuCasa/silabs-firmware#21]
I enabled the multiprotocol support on the SkyConnect, unaware that it needed HomeAssistant OS to properly use it, so I’m trying to revert the firmware using the universal flasher, but it ends up with an Atribute Error.

I’m trying to flash it on a Raspberry Pi with Debian 64-bit and running Home Assistant Supervised.

This is the error that shows up:

Traceback (most recent call last):
  File "/home/pi/.local/bin/universal-silabs-flasher", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1256, in invoke
    Command.invoke(self, ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/universal_silabs_flasher/flash.py", line 151, in main
    if ctx.get_parameter_source("baudrate") != click.core.ParameterSource.DEFAULT:
AttributeError: 'Context' object has no attribute 'get_parameter_source'

**Comment by agners** [comment]
Hm, from what I understand Multiprotocol should work on Supervised (as Supervised is able to install and use add-ons). What isn't working in your case?

The stack trace is from universal-silabs-flasher, best if you create a new issue in this repository for that problem: https://github.com/NabuCasa/universal-silabs-flasher

You can try to use the web flasher at:
https://skyconnect.home-assistant.io/firmware-update/

**Comment by MiloRoNu** [comment]
Thank you for the quick reply.
I tried using the web flasher, but it isn’t working either. I’ve tried with different browsers and computers (A Windows and the raspberry), but it just says it failed to connect.
